# Message template on each event
message:
  join: '§8[§a+§8] §e{player}'
  leave: '§8[§c-§8] §e{player}'
  switch: '§8[§b❖§8] §e{player}§r: §7«{serverFrom}§7» §6➟ §7«{serverTo}§7»'
  chat: '§7[{serverOn}§7]§e{player}§r: {message}'
  block_word: '§8§l» §c你的消息 "{message}" 被禁止发送, 因为包含敏感词 "{blockWord}"'
  list: '§8§l» §7当前共有§6{playerCount}§7名玩家在线: §e{playerList}'

# HttpServer ID and HttpServer Name map, name will be display in message
server_name:
  qq: '§5§l群聊天'

# Http server port, it will use on broadcast and qq
port: 51800

# Broadcast option, set this to broadcast message with other BungeeCord or server
broadcast:
  token: 'token'
  cancel_timeout: 50
  servers:
    - 'host:port'

# Regex rules to ignore message
ignore_rules:
  - '!!.*'

# Block words, a chat message will be blocked if it's include following words
block_words:
  - 'Hello'

# QQ
qq:
  enable: false
  path: '/qq'
  api_url: 'http://localhost:5700'
  message: false
  group_id:
    - 123123123
