ignore_prefix: '!!'
message:
  join: '§8[§a+§8] §e{player}'
  leave: '§8[§c-§8] §e{player}'
  switch: '§8[§b❖§8] §e{player}§r: §7«{serverFrom}§7» §6➟ §7«{serverTo}§7»'
  chat: '§7[{serverOn}§7]§e{player}§r: {message}'
server_name:
  serverID: 'serverName'
broadcast:
  port: 51800
  token: 'token'
  servers:
    - 'host:port'
